### ISSUE TITLE
When I use query('insert into xxx'), it does not insert successfully.

### ISSUE THREAD

**Issue by SeasonPanPan** [kennethreitz/records#224]
**database**: sqlite (also tested in mysql)
```python
create_sql = 'create table test(`id` INT PRIMARY KEY NOT NULL, `name` CHAR(32) NOT NULL)'
insert_sql = 'insert into test(id, name) values (1, "Jim")'
select_sql = 'select * from test;'
delete_sql = 'delete from test;'

db = records.Database('sqlite:///test.db')
db.query(insert_sql)
res = db.query(select_sql)
print(res.all())
```
_The output is "[]"_

I read the source code, and find that if only I use `db.transaction()`, it can work well.
```
 with db.transaction() as tx:
    resi = tx.query(insert_sql)
    print(resi)
res = db.query(select_sql)
print(res.all())
```

**So, is this a problem with my usage?**
Insert operation does not supported in query method?

I searched many blogs, and they write 'db.query(insert_sql)', no one writes 'with db.transaction() as tx', I'm confused.

**Comment by draco1023** [comment]
I got the same issue after updating from `0.5.3` to `0.6.0`.

And the following exception stack trace is always printed when I use records over an SSHTunnelForwarder.

```txt
Exception during reset or similar
Traceback (most recent call last):
  File "D:\app\Scoop\apps\python310\current\lib\site-packages\sqlalchemy\pool\base.py", line 988, in _finalize_fairy
    fairy._reset(
  File "D:\app\Scoop\apps\python310\current\lib\site-packages\sqlalchemy\pool\base.py", line 1438, in _reset
    pool._dialect.do_rollback(self)
  File "D:\app\Scoop\apps\python310\current\lib\site-packages\sqlalchemy\engine\default.py", line 692, in do_rollback
    dbapi_connection.rollback()
MySQLdb.OperationalError: (2013, 'Lost connection to server during query')
```

**Comment by chmelej** [comment]
I got the same issue with postgres

**Comment by mhtvsSFrpHdE** [comment]
Insert not work, 0.6.0 no error, downgrade to 0.5.3 same code trigger
```
Exception has occurred: ResourceClosedError
This result object does not return rows. It has been closed automatically.
```

**Comment by mhtvsSFrpHdE** [comment]
A insert example that use underlying sqlalchemy directly:
```
import sqlalchemy
engine = sqlalchemy.create_engine("mysql://root:password@localhost:3306/schema")
with engine.connect() as conn:
    query = conn.execute(sqlalchemy.text('insert into test (column) values (:row1),(:row2),(:row3)'), {"row1":"r1", "row2":"r2", "row3":"r3"})
    conn.commit()
    if query.rowcount > 0:    # query.rowcount value 3
        pass    
```

What could be wrong that raise `ResourceClosedError`:
```
...
    query = conn.execute(sqlalchemy.text('insert into test (column) values (:row1),(:row2),(:row3)'), {"row1":"r1", "row2":"r2", "row3":"r3"})
    query.all()    # Here raise ResourceClosedError (does not return rows), any that try get row from it will error because insert doesn't get row back
```

So, seems records library doesn't trust it's user will have requirements that insert to database at all.
