### ISSUE TITLE
Error from query with zero rows results via CLI

### ISSUE THREAD

**Issue by cosenal** [kennethreitz/records#62]
If I do a query (via the CLI interface), which returns zero rows, an IndexError is raised.

Example:

```
python records.py 'SELECT * FROM empty_table;' json --url=postgresql://postgres:postgres@127.0.0.1/database
```

This raises the following error:

```
Traceback (most recent call last):
  File "records.py", line 357, in <module>
    cli()
  File "records.py", line 351, in cli
    print(rows.export(arguments['<format>']))
  File "records.py", line 162, in export
    return self.dataset.export(format, **kwargs)
  File "records.py", line 171, in dataset
    first = self[0]
  File "records.py", line 153, in __getitem__
    return rows[0]
IndexError: list index out of range
```

**Comment by varunagrawal** [comment]
PR #65

**Comment by vlcinsky** [comment]
@kennethreitz This issue seems to be fixed.
